### ISSUE TITLE
Email validation on mobile

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#101]
On mobile email validation doesn't seem to work like it does on desktop so the user only sees the error message after they send the message, it also still says it's sent: http://prntscr.com/cn3d26

Not sure if we could do some kind of JS validation ontop of just the normal form email field validation on mobile before the page refreshes @rodica-andronache

**Comment by rodica-andronache** [comment]
@UVLabs I tested too, and I think you're right. I think on mobile, the browser validation for type="email" is not working, and yes, some js check would be needed. Hopefully , we'll have a look on this, next week
