### ISSUE TITLE
Fields misalign on Zerif standard pages

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#102]
@rodica-andronache the fields misalign on standard zerif pages when using the shortcode and makes it not possible to type in the name field, it seems to be caused by this piece of CSS:

![image](https://cloud.githubusercontent.com/assets/10324144/18897806/26b57e06-84fb-11e6-806c-1dbf1736f1fd.png)

Changing the code to width: auto seems to fix the issue, gotten 2 reports on this so far

**Comment by rodica-andronache** [comment]
@UVLabs I need more details here. I tested with both zerif lite and pro, and it seems ok http://dev2.themeisle.com/zerif-lite/sample-page-2/ http://dev2.themeisle.com/zerif-pro/sample-page/

**Comment by UVLabs** [comment]
Strange doesn't seem to happen anymore. Closing.
