### ISSUE TITLE
PHP Strict Standards:  Only variables should be passed by reference

### ISSUE THREAD

**Issue by chesio** [Codeinwp/pirate-forms#104]
Hello,

I'm getting the following notice with version 1.0.17:

> PHP Strict Standards:  Only variables should be passed by reference in /home/wordpress/wp-content/plugins/pirate-forms/pirate-forms.php on line 589

The problematic line reads:

<pre>
$contact_ip = array_pop(explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
</pre>

Since the argument to [array_pop](http://php.net/manual/en/function.array-pop.php) is passed by reference, it shouldn't be an expression, but a variable:

<pre>
$_http_x_forwarded_for = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
$contact_ip = array_pop($_http_x_forwarded_for);
unset($_http_x_forwarded_for);
</pre>

Cheers,
Česlav

**Comment by ineagu** [comment]
@rodica-andronache

**Comment by rodica-andronache** [comment]
Hi @chesio ,

Sorry for the late reply. Thank you very much for the contribution. It will be available in the next update.

Regards,
Rodica
