### ISSUE TITLE
add dashboard widget

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#114]
@contactashish13 like for login customizer we need to add this here too.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/116

**Comment by ineagu** [comment]
@selul I think we can enhance the dashboard widget here to recommend themes/plugins as well, using this model : https://www.dropbox.com/s/jhyx4gdov8f9zyx/Screenshot%202017-05-14%2013.10.59.png?dl=0, maybe pick themes/plugins random from themeisle author ( https://wordpress.org/themes/author/themeisle/ ) and add an install link which will open the default wp popup.

Thoughts ?
