### ISSUE TITLE
Issue with plugin after saving with Zerif Lite

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#115]
@rodica-andronache Contact notification sender email gets over-written with the Contact submission recipients after you save an option in Zerif Lite

**Comment by HardeepAsrani** [comment]
So once you save the settings in Customizer, they are changed here as well.

**Comment by UVLabs** [comment]
@HardeepAsrani was that in reply to me? Did you notice the bug too?

**Comment by HardeepAsrani** [comment]
Just adding up to your findings.

**Comment by UVLabs** [comment]
+1
