### ISSUE TITLE
Change SMTP "password" field to password input type

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#119]
@rodica-andronache it's displayed in plain text: http://prntscr.com/eq6cr7

**Comment by ineagu** [comment]
we need to change this cc @contactashish13

**Comment by contactashish13** [comment]
@ineagu @selul 

Have added this as a branch of #140 

PR: https://github.com/Codeinwp/pirate-forms/pull/148

The build seems to be failing because of something unrelated to the issue
![image](https://user-images.githubusercontent.com/12953439/27920557-9e019510-6292-11e7-993c-c86ed95bc4be.png)
