### ISSUE TITLE
Work on plugin future

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-forms#122]
@selul we should also talk about what are our plans here, no matter what we decide I think is still worth for now to go over the listed issues and make sure the plugin is in a pretty good shape.

**Comment by ineagu** [comment]
Few features that are a must have : 

1. multiple forms
2. mailchimp integration
3. Attachement field should be listed before the recaptcha one and be treated the same ( users can make it required, options, none) + have an optional label.

We can experiment with 1 + 2 in a pro version starting from $19 .

**Comment by selul** [comment]
@ineagu on the way with them :D
