### ISSUE TITLE
New icon & banner image

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-forms#124]
The current icon, doesn't really look like an icon, looks a bit odd on the admin side

**Comment by bogdanpopa90** [comment]
![pirate-forms-featured](https://cloud.githubusercontent.com/assets/23031578/24865410/d6a07386-1e0f-11e7-9226-4a157254d0a9.jpg)
![pirate-forms-featured-2](https://cloud.githubusercontent.com/assets/23031578/24865412/d6c71e6e-1e0f-11e7-9a78-4ba14c74d67b.jpg)
![pirate-forms-icon](https://cloud.githubusercontent.com/assets/23031578/24865411/d6c6a5a6-1e0f-11e7-9a1d-0ff10cae486a.jpg)

**Comment by bogdanpopa90** [comment]
Preview
![preview](https://cloud.githubusercontent.com/assets/23031578/24865575/577008dc-1e10-11e7-9dd6-19c85b92b9a4.jpg)

**Comment by ineagu** [comment]
How the icon looks like in admin?

**Comment by rodica-andronache** [comment]
@bogdanpopa90 that "Contact database" sounds weird for me.  Maybe something like Submissions stored in the database or something else

**Comment by bogdanpopa90** [comment]
![preview2](https://cloud.githubusercontent.com/assets/23031578/24866328/7b33077c-1e12-11e7-90b4-ebf1b10a6391.jpg)

**Comment by ineagu** [comment]
Good for me

**Comment by bogdanpopa90** [comment]
Ok, but first one or second with hands on laptop?

**Comment by ineagu** [comment]
Doesn't matter much for me

**Comment by bogdanpopa90** [comment]
@ineagu Thanks
@rodica-andronache Uploaded files on GDrive
