### ISSUE TITLE
Form alert messages changes have no effect

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#131]
These options: http://prntscr.com/fazv32 are being overridden by HTML5 form alert messages:

![image](https://cloud.githubusercontent.com/assets/10324144/26337476/f9653a0c-3f46-11e7-87b9-6da7439dfc60.png)

**Comment by selul** [comment]
@contactashish13 can you please investigate if we can achieve this.

https://stackoverflow.com/questions/5272433/html5-form-required-attribute-set-custom-validation-message

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/158

**Comment by contactashish13** [comment]
@selul have created a new PR: https://github.com/Codeinwp/pirate-forms/pull/162
