### ISSUE TITLE
refactor pirate-forms 

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#140]
I would need you help in refactor the actual pirate forms plugin: 

* Refactor using the https://github.com/DevinVinson/WordPress-Plugin-Boilerplate structure 
* Currently the boilerplate dont have the autloader in place, we need to have it.
* Fix any additional issues you may see, make sure we have backwards compatibility.
* Add template for the pirate forms contact form, make sure it can gets overwritten in the theme files. Basically i would like the html part to be in a separate file inside the plugin and users will be allowed to extend it in the theme files. The plugin will check for the template file inside the theme ( pirate-forms folder ) and if not exists we load it from the plugin.

**Comment by selul** [comment]
@contactashish13 if you want to have a call before, let me know.

**Comment by contactashish13** [comment]
@selul please check the structure of the theo or the themeisle-coffer plugin. That is the structure I'm using and it contains the autoloader as well. Can you verify that will work for this as well?

**Comment by selul** [comment]
@contactashish13 yes i'm aware of this, it does a very good job, but i like how the boilerplat separate the admin/public logic, loads the assets in a single place and has a wrapper for loading of actions and filters. 

Are you comfortable with trying with this one ?

**Comment by contactashish13** [comment]
@selul sure

**Comment by contactashish13** [comment]
@selul 
* I've reorganized the admin menu so that the settings as well as the CPT are together under one menu.
* There are multiple places that have code related to zerif theme (e.g https://github.com/Codeinwp/pirate-forms/blob/master/pirate-forms.php#L642), I don't know how relevant that is so I've not tested it
* Have fixed an issue that occurs when the same page displays the widget as well as the form through a shortcode

PR: https://github.com/Codeinwp/pirate-forms/pull/141

The PR seems to be failing because the build is somehow not loading ThemeIsle_SDK_Loader

**Comment by selul** [comment]
@contactashish13 i have some concerns here, i have fixed also the sdk loading.

1) The scope of the whole thing is not to move the code around is to make things simple and logic in order to support  further customizations and fixes that might come.  
2) Why we sufix the  constants by __ ? I see these as a common pattern in your development ? Is this important for something ? If is not,  i would like to use them without that prefix. 
3) We have the version in the class-pirateforms, we don't need to have a constant for this. 
4) If we use autloader, we no longer need to require_once the files around the plugin. 

I will add more feedback to the PR.

**Comment by contactashish13** [comment]
@selul 
1. I understand the intent but I was not comfortable with changing everything because the code is not as simple as I was told. That is why I preferred to first move the code around for it to conform to the new structure and then make it more efficient later. If I do everything then the testing cycle will only increase. I felt that this way testing would be broken up into manageable parts. But if you feel we should go the whole hog, I can proceed on it.
2. That's just a habit which I can change
3/4. will check these once you share more feedback

**Comment by selul** [comment]
@contactashish13 yep, i totally understand, i thought that this would be the final version not an intermediate one. 

If you have any other questions let me know. I have shared some feedback on the PR too.

**Comment by contactashish13** [comment]
@selul have made changes so that the code is a more modular. Have also made the widget an autoloaded class but this means we lose backward compatibility because the widget class had to be changed.

**Comment by selul** [comment]
@contactashish13 this is not good, we have a big userbase, around 200k and losing their widget is not a solution. For feedzy lite i had a similar issue and i have included directly the file in the autoloader, you can check the code

**Comment by contactashish13** [comment]
@selul because a widget is registered with the name of its class and I could not find a way around it, I've reverted this change.  The solution in feedzy lite is the same as including the file anywhere else.

**Comment by selul** [comment]
@contactashish13 yes, but i would like to keep all includes in one place, can we move this in the autoloader ?

**Comment by contactashish13** [comment]
@selul done

**Comment by selul** [comment]
@contactashish13 : 

* Please use loader's `add_action` instead of the wordpress add_action, check ( class-pirate-forms.php:166 ) 
* why in autloader are you using two variables `$class` and `$class1` ? Also, i think you can do the `str_replace( '_', '-', strtolower( $class1 ) )` in one place after the namespace check condition and reuse the value in the includes, repeating the same routine of str_replace is not a good idea.
* Build a class  for options set and get, for the moment you are using `PirateForms::pirate_forms_get_key`, i think you can move this in a separate class which will handle the options ( setting and getting them). Also the prefixing the method with the plugin name is not really necesarry, we could use something like `PirateForms::get_option`
* Once that we make the option wrapper class, we dont need to use update_option, get_option or anything related, just use the class methods.
* for methods and local variables we don't need to use pirate_forms prefix anymore, it's hard to understand and follow, we can use more explicit name for them. 
* Try to clean the admin options page a bit, we can separate the views into content and sidebar, for sidebar use an action which all the sidebar boxes can hook there. We can leverage the use of action hook for sidebar boxes and separate their loading into separate files for a more logical code. 

* think of some relevant phpunit test cases, we would need as much as possible.

**Comment by contactashish13** [comment]
@selul I've incorporated your suggestions. I'll work on the test cases as well.

**Comment by contactashish13** [comment]
@selul have added test cases as well
