### ISSUE TITLE
title->subtitle spacing on front

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-forms#143]
Especially for latest 2 sections the spacing between title and subtitle is a bit odd : 

https://www.dropbox.com/s/ya4ervu22zve199/Screenshot%202017-06-29%2017.47.13.png?dl=0, here is the spacing on materialkit, I think we can emulate that one : https://www.dropbox.com/s/lfwy33bknb85tuc/Screenshot%202017-06-29%2017.49.24.png?dl=0

**Comment by rodica-andronache** [comment]
@ineagu this is for hestia right? Should I move it there?

**Comment by ineagu** [comment]
right
