### ISSUE TITLE
reCaptcha shows after click on any field

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/pirate-forms#144]
reCaptcha is not showing in the form initially, it appears after clicking on any form field. If you click one of the text boxes in the form the recaptcha will appear. 

Helpscout thread https://secure.helpscout.net/conversation/389685749/136849/
https://secure.helpscout.net/conversation/387473851/136589/?folderId=212390

**Comment by rodica-andronache** [comment]
@poonam279 this is how it was designed, to appear after the message field si focused, so I think maybe the customer in the first HS thread may have a different problem.
I also agree, that maybe this behavior can be changed somehow, or a new option added :)

**Comment by HardeepAsrani** [comment]
I think of it as a good feature. Maybe adding a notice about it in the backend so the user knows.

**Comment by selul** [comment]
Let's see if there are more users requesting it. We can postpone this for later iterations.
