### ISSUE TITLE
Pirate Forms nags user roles with no plugin or theme rights

### ISSUE THREAD

**Issue by breescorner** [Codeinwp/pirate-forms#149]
Hello... I use zerif lite theme but don't use pirate forms and have not installed it. For users with no access to mess with plugins, theme, etc... they open the dashboard to a constant nag telling them they have install rights. Is there a way to stop this, so only admin can see it?

**Comment by selul** [comment]
@breescorner can you show me a screenshot about the nag you are talking about ? Thanks !!
