### ISSUE TITLE
test round 

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#155]
@contactashish13 i would like to test this new version having the Zerif theme installed. Into Zerif customizer we have some controls that will sync with the pirate forms options. 

1.  I would like to test changes with the old version installed and after that switch on the new version and see if the workflow is working the same. 
2. Please test if the form shortcode and widget is displaying same in the old and pro version. 

Let me know if you have any questions.

**Comment by contactashish13** [comment]
@selul I see the options but I dont see how it creates a contact us page. can you please explain the process?

**Comment by selul** [comment]
@contactashish13 can you try to dig a bit and understand the logic, i'm not sure about what you are talking about either.

**Comment by contactashish13** [comment]
@selul have had to make a few corrections. PR: https://github.com/Codeinwp/pirate-forms/pull/166
