### ISSUE TITLE
create html helper classes

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#156]
@contactashish13 i would like to create 2 html helper classes which will handle the fields in the settings area and public form. Basically one would be for admin and one for public view.

Each class will have methods to add different types of controls according to the current html. 

They will be used following this pattern.
```
$admin_html->add_text( args ( ... ) )  // For input text.
$admin_html->add_password( args ( ... ) )  // For input password
$admin_html->add_textarea( args ( ... ) ) // For input textarea.
... 
```
The admin options and form elements will be configured using a variable which will contain argument for each type of input: 

```
 $admin_options = array(
 'section_name'=>array(
       'name' => 'Section name',
       'controls' => array(
            array (
                  'type'=>'text',
                  'label'=>'Form name',
                  .... Other relevant arguments.

            ) 
       )
 );
) 
```

Before rendering the options variables, i would want to apply a filters for each one, 
```
$admin_options = apply_filters('pirate_forms_admin_controls',$admin_options);
$form_options = apply_filters('pirate_forms_public_controls',$form_options);
```

Let me know if you have  any questions else.

L.E: The scope of this is tu have two utility classes for handling all controls, either admin or public view. Because the public view is kind of different from the admin one, we would need different output. Using this classes we will use the configuration variables to add form elements and those would be easly extended in the pro or other 3rd party themes or plugins.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/157

I've added only one HTML helper class. I've also made the content inside the tabs more similar to each other with the tooltip popups.

I don't know why the build is failing. PHPCS works properly at my end.

**Comment by selul** [comment]
@contactashish13 you need to update your wordpress coding standards to the latest, as it was a release recently and also the phpcs package to 2.9.0

**Comment by contactashish13** [comment]
@selul thanks! The build is fine now.

I was curious to understand how you knew that was the error. I don't see any explanation displayed on travis.

**Comment by contactashish13** [comment]
@selul I've issued a new PR https://github.com/Codeinwp/pirate-forms/pull/161
