### ISSUE TITLE
build docs

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#168]
@contactashish13 having the recent changes can you help me build a two simple docs

*  on what actions and filters can users can use in the current version, what parameters does each one send and a bit of details about the context where is used each one. You have here the doc where you can start writing: 
https://secure.helpscout.net/docs/56221c6d903360610fc69003/article/597ef76e2c7d3a73488b7d78

* How users can overwrite the default form template in they theme folder. 
https://secure.helpscout.net/docs/56221c6d903360610fc69003/article/597ef859042863033a1b7ddc 

You can wrap the code snippets in `<pre>` or `<code>` tags.

**Comment by contactashish13** [comment]
@selul I assume you want the actions/filters that are defined specifically for the plugin and not the native/WP one that are being used in the plugin, right?

**Comment by contactashish13** [comment]
@selul If this is for end users, then there are no actions or filters for their use.

There are 3 actions we have defined for loading the sidebar in the admin screen:

- pirate_forms_load_sidebar
- pirate_forms_load_sidebar_theme
- pirate_forms_load_sidebar_subscribe

I believe none of them can be used by end users. Can you please clarify?

**Comment by selul** [comment]
@contactashish13 i'm interested for this: 
Actions:
* **pirate_forms_before_sending**
* **pirate_forms_after_sending**

Filters: 
* pirateform_wrap_classes_name
* pirateform_wrap_classes_email
* pirateform_wrap_classes_subject
* pirateform_wrap_classes_message
* pirateform_wrap_classes_attachment
* pirateform_wrap_classes_captcha
* pirateform_wrap_classes_submit
* pirate_forms_public_controls
* pirate_forms_admin_controls
* pirate_forms_admin_controls_for_options
* pirate_forms_admin_controls_for_fields
* pirate_forms_admin_controls_for_field_labels
* pirate_forms_admin_controls_for_alerts
* pirate_forms_admin_controls_for_smtp

**Comment by contactashish13** [comment]
@selul done. can you please check?

**Comment by selul** [comment]
Great. Well done.
