### ISSUE TITLE
add classes to the form tag

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#179]
@contactashish13 i would like to add to the form tag, css classes according to the fields they have.

If they have subject enabled, the form will have `pirate-forms-subject-on`, if the email the email field, we will have  pirate-forms-email-on, and so on. 

This will help us and users style the form according to the fields that it has.

Thanks !

**Comment by contactashish13** [comment]
@selul have addressed both #178 and #179 in this PR: https://github.com/Codeinwp/pirate-forms/pull/180
