### ISSUE TITLE
Notification Email not being sent

### ISSUE THREAD

**Issue by rgallison** [Codeinwp/pirate-forms#185]
Hi.  I installed Pirate Forms Plugin, configured everything, including adding sender email, recipient email, and mandrill smtp.  But I'm not getting the notifications when I submit the form.

**Comment by selul** [comment]
@rgallison can you contact us at themeisle.com/contact for a more in depth debug analysis ? Please reference this issue when contacting.

ThankS !

**Comment by rgallison** [comment]
I forgot to reference this issue :/
