### ISSUE TITLE
Remove or make additional email info optional

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/pirate-forms#198]
A user suggested to make the last three items of an email optional or remove them: https://www.dropbox.com/s/yhnw94ir1myge2s/Screenshot%202017-09-11%2016.27.33.png?dl=0

As the user doesn't want to person to see this info and it appears in the quote of the email. It can be option or removed, and saved only to its stored post type.

Thoughts? @ineagu @selul @rodica-andronache

**Comment by selul** [comment]
in the latest version, user can completely customize http://docs.themeisle.com/article/779-how-to-change-default-email-content-in-pirate-forms
