### ISSUE TITLE
Contact Form Freeze

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/pirate-forms#205]
Between 768px - 992px **Subject** placeholder is on the wrong line and make **Name** and **Email** fields unclickable.

http://prntscr.com/gr3a22
https://secure.helpscout.net/conversation/438418411/143922/?folderId=212385

**Comment by selul** [comment]
this should be fixed in latest ones

**Comment by rodica-andronache** [comment]
is still happening https://prnt.sc/gwhgl5

**Comment by selul** [comment]
@contactashish13 can you have a look.

**Comment by selul** [comment]
@bogdanpopa90 can you have a look when you got a bit of free time.

**Comment by stefan-cotitosu** [comment]
I tested it and it is not working at my end.
