### ISSUE TITLE
still asking for install even if plugin is installed

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/pirate-forms#223]
@selul I was testing pirate form and for some reason, on my device, it keeps asking to install the plugin even thou it is installed -> http://prntscr.com/h6tjc5

maybe we should take a quick look?

**Comment by selul** [comment]
@dascalescuro incearca sa scoti ce pluginuri mai ai si tema si vezi daca mai ai asa.

**Comment by dascalescuro** [comment]
@selul cu pluginuri dezactivate exceptand pirate forms dar cu tema activa (Zillah) apare mesajul: http://prntscr.com/h6tqjw

cu alta tema activa (Twenty Fifteen/hestia) si doar pirate forms nu mai apare niciun mesaj.

cu Zillah activat si Pirate Forms activat apare iar: http://prntscr.com/h6trbi

cumva doar cu Zillah activat mesajul continua sa apar...

**Comment by selul** [comment]
da, pai e din zillah mesajul/problema.

**Comment by ineagu** [comment]
the message is there because of the slug, I think tgm check the slug and if the slug doesn't match still shows that. or not tgm, but our system
