### ISSUE TITLE
add wysiwyg editor for email 

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#231]
@contactashish13 i would like to add wysiwyg  editor in the free and pro version, for customizing the email sent  to admin ( the one that we store in entries ) 

For the lite version, we will add this in the field labels area. For the pro version, in the behavior tab, as the first field.

User will be able to use magic tags, as {email}, {ip},{name}, having a magic tags for all the fields used in the current email template, as well as adds a new magic tag for each field that they add in the pro version. 

We will also show in the field description the available magic tags.

You need to be aware that one form may have different magic tags from another, as the custom fields will be also different one from another. 

Let me know if you have any questions.

**Comment by contactashish13** [comment]
@selul 

> For the pro version, in the behavior tab, as the first field.
Behavior tab or form fields tab?

> User will be able to use magic tags, as {email}, {ip},{name},
should we add a tinymce button to insert the magic tags?

**Comment by selul** [comment]
@contactashish13 yes, behavior tab. 

We can keep them in the description, but make sure we show all available ones.

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/pirate-forms/pull/235 and https://github.com/Codeinwp/pirate-forms-pro/pull/43
