### ISSUE TITLE
load js only when needed

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pirate-forms#233]
cc @selul @contactashish13

**Comment by selul** [comment]
@contactashish13 we will need to enque the css and js only when the form template is called, similar how we are trying to do with wppr. 

The intent is to not load the plugin assets all over the frontend, if the form is not used on that particular page.

**Comment by contactashish13** [comment]
@selul I've tested with the master branch and this seems to be already the case. If a page does not have the form, no resource is loaded.

**Comment by ineagu** [comment]
I think I saw it on justfreethemes home page mayeb

**Comment by selul** [comment]
@ineagu i can confirm that is nothing like this present. i think ash is right.
