### ISSUE TITLE
Name field not working

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/pirate-forms#236]
A client reported that on this page, from mobile the name field is unclickable. Most of the support team members were able to replicate the issue on Android phones. I am not sure about iOS.

http://prntscr.com/hdb3n8

This is the page where we tested this.
https://demo.themeisle.com/pirate-forms/phone-number-form/

**Comment by rodica-andronache** [comment]
@bogdanpopa90 I tested on my local, and I think it's happening because of `.pirate_forms_wrap{ float: left }`. I tested with Pirate Forms only. Not the Pro version. Could you please check this tomorrow, for both lite and pro? 👍

**Comment by selul** [comment]
@bogdanpopa90 please fix the checkbox issue on custom trap when you finish this.

**Comment by rodica-andronache** [comment]
@bogdanpopa90 is this finished?

**Comment by bogdanpopa90** [comment]
@rodica-andronache Yes
