### ISSUE TITLE
Spam label issue on page with 2 forms

### ISSUE THREAD

**Issue by bogdanpopa90** [Codeinwp/pirate-forms#250]
For example, if we have two forms in same page, the first one in content and the second in sidebar like a widget with Custom spam option selected, when you click on second form label the checkbox of first form is selected.

This happens because both checkboxes have same #id. We should be able to create a unique id for every antispam checkbox.

Screenshot: http://prntscr.com/hkql6a

**Comment by selul** [comment]
@contactashish13 can you check

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/278
