### ISSUE TITLE
There's no option to add row in the table given in default form

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/pirate-forms#253]
@selul @contactashish13 There should be an option to add more rows in the default table of the default form. i.e.:
![screen shot 2017-12-19 at 2 35 03 pm](https://user-images.githubusercontent.com/3204558/34150708-29406c64-e4cf-11e7-8def-04bf73b3eaab.png)

Also, If a user enters the magic tags outside the table, i.e.:
![screen shot 2017-12-19 at 2 31 28 pm](https://user-images.githubusercontent.com/3204558/34150755-51742a0e-e4cf-11e7-9c22-0a083d098f78.png)

The email received is not as per the formatting, i.e.:
![screen shot 2017-12-19 at 2 30 31 pm](https://user-images.githubusercontent.com/3204558/34150782-698b992e-e4cf-11e7-84d4-b3ad9c9572de.png)

**Comment by selul** [comment]
i think now is possible using the text view.
