### ISSUE TITLE
There should be some more important fields for the user in default forms

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/pirate-forms#254]
@selul @contactashish13 The options in default forms are:
![screen shot 2017-12-19 at 2 35 03 pm](https://user-images.githubusercontent.com/3204558/34151027-1907eace-e4d0-11e7-8330-218d05234c96.png)

I guess, the user who just want a simple form, might need some useful information like: 
Name, Message, and Subject. i.e.
![screen shot 2017-12-19 at 2 55 58 pm](https://user-images.githubusercontent.com/3204558/34151463-4f22f15c-e4d1-11e7-80ce-88473f7660c9.png)

Even If the test email is sent, It would be like: 
![screen shot 2017-12-19 at 2 56 41 pm](https://user-images.githubusercontent.com/3204558/34151483-63045648-e4d1-11e7-894b-4160b6ad3598.png)

**Comment by selul** [comment]
@contactashish13 can you check ?

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/255
