### ISSUE TITLE
User should be provided the access to both visual and text editor tabs in default form 

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/pirate-forms#256]
@selul @contactashish13 When editing email content in form labels tab, the user should be given both visual and text editor of wysiwyg so that they can add/remove the table rows for email content.

**Comment by selul** [comment]
@contactashish13 let's tackle this.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms-pro/pull/66 and https://github.com/Codeinwp/pirate-forms/pull/289
