### ISSUE TITLE
File Not Included + Code not Working to include + SendInblue API not working

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/pirate-forms#262]
So, I was testing the email subscription form:

![screen shot 2018-01-10 at 1 34 47 am](https://user-images.githubusercontent.com/3204558/34740751-83477fee-f5a6-11e7-88a8-5cf64de5266b.png)

And then I get error:

![screen shot 2018-01-10 at 1 36 10 am](https://user-images.githubusercontent.com/3204558/34740843-c86f6168-f5a6-11e7-9a65-be6bec3de068.png)

So I tried fixing this code [here](https://github.com/Codeinwp/pirate-forms/blob/34659334c7265c1782a340d7e25c95db88fc603c/admin/partials/pirateforms-settings-sidebar-subscribe.php#L29) `require( PIRATE_FORMS_PATH . 'mailin.php' );` to `require( plugin_dir_path( __DIR__ ) . 'mailin.php' );` and found out that the file doesn't exists. So I added the file from Login Customizer [here](https://github.com/Codeinwp/login-customizer/blob/master/mailin.php) in the same directory and found this error:

![screen shot 2018-01-10 at 1 42 16 am](https://user-images.githubusercontent.com/3204558/34741177-c4763838-f5a7-11e7-9839-e4381774bdd2.png)

Now, i haven't worked with sendinblue API. @selul @contactashish13 what do you suggest should be done next?

**Comment by rohittm** [comment]
So, the problem is fixed. The cURL wasn't able to fetch the details in my installation. But I checked it in other installations, and It is working now. 

@selul check PR #263

**Comment by selul** [comment]
@contactashish13 @rohittm can we include the composer library instead that we use now? Also, when loading the maillin class, be sure to do the collision check ( checking if that class exists already ).

**Comment by contactashish13** [comment]
@selul The composer libraries were removed because they conflicted with the official plugins: https://github.com/Codeinwp/pirate-forms-pro/commit/24d42aa1b7636ce9f7c585aec189f6d7b1d21888

**Comment by selul** [comment]
i don't get your point

**Comment by contactashish13** [comment]
if you remember, we had a ticket on helpscout where the user complained that they had sendinblue plugin installed and pirate forms was conflicting with that. This is because the official plugin does not check for conflicts. That is why we had to remove this from composer and manually include the file. We did this for most libraries. Please check the commit mentioned above.

**Comment by selul** [comment]
I get your point now. Yes, we should be checking the library existence first and then load it, same thing as we do in pf-pro @rohittm

**Comment by contactashish13** [comment]
@selul it doesn't work.. The official plugins don't check before loading the class that is why I had to remove all the libraries from composer.

**Comment by selul** [comment]
@contactashish13 yes, i get it, i mean in pirate forms lite, we should do the same logic as we do in pro for using that subscribe widget.

**Comment by rohittm** [comment]
@contactashish13 @selul PR #268

**Comment by selul** [comment]
@rohittm i've added one small comment.

**Comment by rohittm** [comment]
@selul I don't understand.

**Comment by selul** [comment]
the comment is in the pr.

**Comment by selul** [comment]
@rohittm sorry, i wanted to comment on another issue.
