### ISSUE TITLE
Send message button  issue with Hestia

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/pirate-forms#265]
@selul @rodica-andronache If we add two words inside the Send button, the CSS will break. Please see the image attached:

<img width="1324" alt="screen shot 2018-01-17 at 5 15 14 pm" src="https://user-images.githubusercontent.com/6906834/35050536-bdf42a4c-fbab-11e7-926e-3f9cecd2b78f.png">

**Comment by mileamadalin** [comment]
@selul we have a similar issue with the Parallax One theme. The "Send" button was added to the left of the forum if the recaptcha is enabled. 

![screen shot 2018-01-18 at 12 04 40 pm](https://user-images.githubusercontent.com/6906834/35092361-cc837030-fc47-11e7-8a43-5eb19e42fdad.png)

The customer website: http://www.lynxytrading.co.uk/
Ticket: https://secure.helpscout.net/conversation/505751468/152334?folderId=212385

As a possible fix Ionut suggested to remove the `float: none; ` I personally recommended to our customer to add `float: left;`

**Comment by ineagu** [comment]
@abaicus we'll probably need at some point  to look on this and how pirate forms generally work in various contexts

**Comment by ineagu** [comment]
the problem seems to be a combination of adding of the table-cell thing and float none: https://www.paleodata.com/contact/

**Comment by abaicus** [comment]
@ineagu it surely is table cell... but if the button text is longer we need to give up table cell... :(

**Comment by abaicus** [comment]
@mileamadalin This should work ok now.

**Comment by mileamadalin** [comment]
@abaicus Thanks!
