### ISSUE TITLE
Send copy of email to sender

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/pirate-forms#269]
A lot of people have asked an option that they can enable to send a copy of the sent email to the sender. @selul

**Comment by selul** [comment]
@HardeepAsrani not sure if we have this already or not, @contactashish13 can you confirm ?

**Comment by contactashish13** [comment]
@HardeepAsrani if the option is selected, the sender of the email is sent a confirmation email. This is not the same as the copy of the email originally sent. @selul should this feature be added?

**Comment by selul** [comment]
we can work on it, i've added it in the backlog.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms-pro/pull/54 and https://github.com/Codeinwp/pirate-forms/pull/275

If the user enables this, the original email will be added to the confirmation email that is sent to the sender.

**Comment by selul** [comment]
@contactashish13 can we do any unit test to cover this ?

**Comment by contactashish13** [comment]
@selul have added the test case only in free. I don't think its required in PRO because the functionality resides in free.
