### ISSUE TITLE
Allow .zip attachments

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/pirate-forms#271]
We can also allow .zip attachments as people might be sending multiple files.

**Comment by selul** [comment]
@contactashish13 can you check if already support this  ?

**Comment by contactashish13** [comment]
@selul I've added additional support for all types here https://en.support.wordpress.com/accepted-filetypes/

Also, when an invalid type was being uploaded, no error was being shown. Have corrected this as well.

PR: https://github.com/Codeinwp/pirate-forms/pull/281
