### ISSUE TITLE
Redirect to a certain area of the page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#273]
After submitting the form, for Hestia and Zerif users for example, they are redirected to the top of the page, and can't see the result messages ( either success or error messages ) as the front page contact section is at the bottom of the page.

In Zerif Pro, we have this done, but it's working with the theme's own contact form, not Pirate Forms.
Not sure what the best approach would be here.

https://wordpress.org/support/topic/how-to-redirect-to-the-contact-section-of-the-welcome-page-after-form-submission/

**Comment by selul** [comment]
@contactashish13 when the form is submitted and the page gets refreshed, we need to send users to the contact area. I assume that each form has a unique id, we can append that id to the URL, like http://site.com/#contact-form

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-forms/pull/279

I've tested with Hestia Pro, Zerif Lite/Pro and with a default WP theme. I've also tested with multiple forms on the same page.
