### ISSUE TITLE
The page must not reload after submission of form

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/pirate-forms#274]
@selul @contactashish13 

Just an idea. If someone submits the form on on any page, the page reloads and displays the 'Thank You' message above the form fields. We can make an AJAX call or something, to not reload the page and display the thank you message.

for reference: https://wordpress.org/support/topic/how-to-redirect-to-the-contact-section-of-the-welcome-page-after-form-submission/

**Comment by rodica-andronache** [comment]
this will be available in the next release
