### ISSUE TITLE
Contact Us Section Button Colors not Changing

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/pirate-forms#28]
The menu for changing the colors of the button in the contact us section does not seem to be actually changing the colors.
This happens only with Pirate Forms. After disabling the plugin the button color changed.

**Comment by rodica-andronache** [comment]
@alexandrastann can you check if this is still happening? Also, was this for Zerif PRO? Have you tried changing the colors from here: http://prntscr.com/ad4j91? For me it's working

**Comment by HardeepAsrani** [comment]
Also we should close this. :)
