### ISSUE TITLE
 GDPR compliant

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#295]
@contactashish13 what we need here:
- [ ]  Move here the checkbox field which is not available just in the pro version ( to allow users to add a GDPR checkbox )
- [ ] Disable by default the 'Store submissions in the database' option
- [ ] When the 'Store submissions in the database' option is activated, if the user doesn't have a checkbox field enabled (for each form created), add a notice "According to GDPR we recommend you to ask for consent in order to store user data."

https://github.com/Codeinwp/pirate-forms-pro/issues/68

**Comment by rodica-andronache** [comment]
@contactashish13 no, the checkbox in not a specific one to GDPR. Any checkbox the user might add

**Comment by rodica-andronache** [comment]
@contactashish13 for the first question yes to all three a, b and c.
for the second question, I was thinking of an admin notice, but maybe you could try and see how it would look under the store in db checkbox?

**Comment by contactashish13** [comment]
@rodica-andronache I had a thought. Maybe users want to provide a link to terms and conditions. With our proposed implementation (and current implementation in pro), users can only provide plain text field. To enable users to do that, maybe we should give a WYSIWYG field for the checkbox link? Or should we do this through filters?

**Comment by rodica-andronache** [comment]
@contactashish13 yes, it's a great idea. you can try with the WYSIWYG

**Comment by contactashish13** [comment]
@rodica-andronache 

I have added the message 

- on hover as a title attribute
- in the label popup/description
- as an admin notice

PR: https://github.com/Codeinwp/pirate-forms-pro/pull/69 and https://github.com/Codeinwp/pirate-forms/pull/297

The lite build failed because Wraith failed. Maybe Wraith should be part of allowed failure like in all other repos?

**Comment by rodica-andronache** [comment]
@contactashish13 yes, you can change the travis.yml file to allow wraith to fail

**Comment by rodica-andronache** [comment]
@contactashish13 I would also make the notice dismissable. 
And in PRO , the checkbox appears before the message box  https://prnt.sc/jdlzzn, not sure that's ok

**Comment by contactashish13** [comment]
@rodica-andronache checkboxes are usually before the labels :) Even on google captcha or even https://github.com/Codeinwp/pirate-forms/issues/295#issue-317597173

**Comment by rodica-andronache** [comment]
@contactashish13 no, what I mean, is that the checkbox field is not at the end of the form, where I would expect it, as it is in the lite version.
But it's at in the middle of the form ( where all the other custom fields are added ).

**Comment by contactashish13** [comment]
@rodica-andronache custom fields are inserted before the message box and because this checkbox is part of the custom field list, it is inserted before the message box. 

In lite, it is a separate entity so it can be shown wherever required.

**Comment by rodica-andronache** [comment]
@contactashish13 yes, I know why it's displayed there, I was wondering if it would be possible to add it at the end in pro too, as usually, the checkbox is at the end, at least this is how I see it :) 
And for the dismissible notice, just adding the dismissible isn't enough, as it will come back again and again. I think you need to use a meta and store it in the database, to make the it really dismissible. Maybe take a look here https://github.com/Codeinwp/themeisle-companion/blob/06f60f18de8261510adc032abd300e6ca0e7a946/core/app/class-orbit-fox-admin.php ?

**Comment by contactashish13** [comment]
@rodica-andronache right, I wanted that confirmation you want it to be actually dismissed rather than just be dismissible :)

any suggestions on how to handle the pro checkbox?

**Comment by rodica-andronache** [comment]
@contactashish13 regarding the notice, I'm not sure I'm understanding.
So, for Pirate Forms, the notice will appear only when the Store in database option is selected and there isn't a checkbox field in the form.
For Pirate Forms PRO, the notice will appear only when the Store in database option is selected and **at least one** of the forms doesn't have a checkbox field. 
How does this influence the dismissible notice? You can just add a meta like here https://github.com/Codeinwp/themeisle-companion/blob/06f60f18de8261510adc032abd300e6ca0e7a946/core/app/class-orbit-fox-admin.php#L144 in the notice box, and once that notice close button is clicked, update the meta with false or something, and make sure the notice is not displayed anymore. Does this make sense? :)
About the checkbox in pro, I don't really know,I still don't know the code very well, I see that the field is a repeater, but I was thinking that maybe there is a way to get only the checkbox out of that and display it at the end of the form. But I don't know if it's possible and how hard would it be.
What about moving the checkbox field outside the repeater and make it a stand-alone field like the other ones? Would it be possible? ( maintaining the old options for users that already had this )

For now, we can at least, have the dismissible notice in place, to release the lite version, until we decide on the pro 👍

**Comment by contactashish13** [comment]
@rodica-andronache for pro, let's say there are 5 forms out of which 4 do not comply with our rule. The user will see 1 notice and dismiss that. It will effectively dismiss the notice for all 4 forms, not just for 1 form. Do you want this behavior?

> but I was thinking that maybe there is a way to get only the checkbox out of that and display it at the end of the form

this might not be a good idea because if users have already created a checkboxes in a particular sequence, this will destroy that. This is the same reason why moving all custom fields after the message box might also be a bad idea.

> What about moving the checkbox field outside the repeater and make it a stand-alone field like the other ones? 

This would be the most preferred behavior but this would effectively mean you are trying to specifically support GDPR. That is why I had initially asked if that was the intent. But, if we are not going to call this field GDPR or something similar, then how will we ensure that users are not confused about this standalone checkbox vs the checkbox they can create using custom fields?

**Comment by rodica-andronache** [comment]
@contactashish13 ok, for the pro, we'll leave it like this. I forgot that Marius told me that we'll add the possibility to sort the fields in the near future, so that will fix this at that point in time.
For the notice, just one notice, that will constantly appear no matter how many forms you have ( only when the Store in database option is selected and **at least one** of the forms don't have a checkbox field  - make sure this is how it's working ) , and if they dismiss it, it will not appear anymore.
Hope it's clear now, sorry for all the hassle :D

**Comment by contactashish13** [comment]
@rodica-andronache the pro notice and the free notice is the same. So, if the user dismisses any of these notices, it will not pop up ever again. 

I don't think this is the correct behavior. Consider this scenario:

1. User creates form with our rules (our rules = Store in database option is selected and form has checkbox). Created this field NOT for GDPR.
2. Dismisses the notice.
3. Creates another form with our rules. This is with a checkbox for GDPR.
4. Does not see the notice because it was dismissed and has forgotten about it. 

Is this the behavior you want?

**Comment by contactashish13** [comment]
Yes there will be multiple but each will be dismissible. If they are not dismissible then they would be irritating :) Basically each form will have its dismissible notice. If you check, in each notice I display the name of the form as well so that the user knows which form is problematic.

There will be one notice for the lite form as well.

Think of a scenario where the user has dismissed a notice in lite and then upgraded to pro. He will never see a notice in pro.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, let's do that :)

**Comment by rvoortman** [comment]
I want to add another feature; most people don't really need to the Ip-address, maybe it's an idea to disable the tracking of the IP address.

**Comment by contactashish13** [comment]
@rodica-andronache done.

**Comment by rodica-andronache** [comment]
@contactashish13 in the All forms page https://prnt.sc/jeswx3 the notice can't be dismissed, it reapers after each refresh

**Comment by contactashish13** [comment]
@rodica-andronache I've tested this and it seems to work fine for me. Each form has its own notice (prefixed with the form name).

**Comment by dascalescuro** [comment]
another good idea is to send the copy of the form to the person that submitted it :)

**Comment by rodica-andronache** [comment]
@contactashish13 is this what this option does https://prnt.sc/jo7yyc ? What Claudiu mentioned, to send a copy to the person that submitted it.
If so, could you make sure you or @rohittm make this more clear in the GDPR documentation? Let me know :D

**Comment by contactashish13** [comment]
@rodica-andronache "Contact notification email address" is used as the from email ID when the mail is sent to email ids in "Contact submission recipients".

In order to send a copy to the submitter, "Add copy of mail to confirmation email" and "Send email confirmation to form submitter" should be checked.

**Comment by dascalescuro** [comment]
another good read is this roadmap: https://calderaforms.com/gdpr/

**Comment by rodica-andronache** [comment]
ok, @rohittm could you please update the doc with this thing? how to send a copy to the submitter

**Comment by rohittm** [comment]
Sure, I will 👍

**Comment by rodica-andronache** [comment]
@contactashish13 let's also add an option to disable the tracking of the IP address, just after the option to 'Store submissions in the database'. 
And let's make it by default **true**, meaning that we'll no longer track the IP, store it in the database and show it in the email content **by default**. 
Let's also add the message "According to GDPR, we recommend you to ask for consent in order to store user data." for this option too.

And have this in lite and pro.

After that, @rohittm please mention it in the Pirate Forms documentation and the GDPR one.

Thanks :)

**Comment by contactashish13** [comment]
@rodica-andronache 

1. Maybe we should make it similar to the store submissions checkbox i.e. unchecked by default and the label reading "Track IP". It will be more consistent.
2. The IP is also used for checking whether its a blacklisted IP (from the WP discussion settings) and whether its spam (using akismet). If the user does not enable tracking of IP, should these functionalities also not use the IP?

![image](https://user-images.githubusercontent.com/12953439/40824454-d45a3740-6591-11e8-92f2-fc06fb98e993.png)

**Comment by rodica-andronache** [comment]
@contactashish13 yes for both 👍 thank you

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/pirate-forms/pull/322

**Comment by rodica-andronache** [comment]
@contactashish13 we should have this for pro too, right?

**Comment by contactashish13** [comment]
@rodica-andronache we aren't tracking IP in pro.

**Comment by rodica-andronache** [comment]
@contactashish13 
isn't the same thing as for the store in the database option which is separated in pro for each form?
https://prnt.sc/jx5idd

**Comment by contactashish13** [comment]
@rodica-andronache its already part of pro.

**Comment by rodica-andronache** [comment]
@contactashish13 how is it working in pro? I don't see any option for that, for each individual form
Plus, I got this for one form with Pirate Forms and Pirate Forms Extended both from the development branches https://prnt.sc/jxlkqk. Do you know what may cause this?

**Comment by contactashish13** [comment]
@rodica-andronache here is my commit. I don't know how to search for it but it seems like things have got messed up while merging. Also I'm not sure why PRs against #295 have been merged when they are still only half-developed.

![image](https://user-images.githubusercontent.com/12953439/41721664-24d4e984-7584-11e8-84e3-1c2fc5578d95.png)

**Comment by rodica-andronache** [comment]
@contactashish13 I'm not sure, maybe I've messed the PR. But I can't find here the branch from the screenshot https://github.com/contactashish13/pirate-forms-pro . Only in lite, which is already merged on dev. Maybe you can add the commit again?

**Comment by contactashish13** [comment]
@rodica-andronache I've added this back. And also added support for aweber and campaign monitor (#310) PR: https://github.com/Codeinwp/pirate-forms/pull/324 and https://github.com/Codeinwp/pirate-forms-pro/pull/77

PS - I think this will need major testing :)

**Comment by rodica-andronache** [comment]
ok 💃  @rohittm can you please test and make a small report https://github.com/Codeinwp/pirate-forms/pull/324 and https://github.com/Codeinwp/pirate-forms-pro/pull/77

Test the integrations from here https://github.com/Codeinwp/pirate-forms/issues/310
and the option to stop tracking the IP in the pro version
