### ISSUE TITLE
reCaptcha without refresh 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/pirate-forms#296]
@rodica-andronache @HardeepAsrani We have a customer that wants to be able to send a message from Contact Form with the reCaptcha activated but without refreshing the page. 

https://secure.helpscout.net/conversation/569461537/160108?folderId=948378

I found some solutions for that, but still not sure if that is the best practice.

**Comment by rodica-andronache** [comment]
this will be available in the next release
