### ISSUE TITLE
Load reCAPTCHA assets only when required

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/pirate-forms#301]
ref https://secure.helpscout.net/conversation/581079705/161641

**Comment by rodica-andronache** [comment]
@rohittm for me, this seems ok, but could you please take another look here? Make sure both the lite and pro versions work well 👍

**Comment by rohittm** [comment]
@rodica-andronache  @contactashish13 

So, here are my tests:

1. With the lite version. There's no error and it is working fine. 
2. With pro version. The site key and secret key were there in input already. Also, it worked fine.
