### ISSUE TITLE
add ajax support

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/pirate-forms#305]
ref https://secure.helpscout.net/conversation/569461537/160108

**Comment by rodica-andronache** [comment]
not related to this, but I also saw this notice https://prnt.sc/jknq6t

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/pirate-forms/pull/307 and https://github.com/Codeinwp/pirate-forms-pro/pull/71

I've tested the below scenarios:
1. default form + widget (combination of submit and ajax)
2. default form + custom form + widget (combination of submit and ajax)

**Comment by rodica-andronache** [comment]
@contactashish13 I tried just https://github.com/Codeinwp/pirate-forms/pull/307 with [pirate_forms ajax="true"] in a post, and it doesn't seem to work with ajax. Am I missing something?

**Comment by contactashish13** [comment]
@rodica-andronache its ajax="yes" or ajax="no" :)

**Comment by rodica-andronache** [comment]
@rohittm plus after the release, please create a new form on the demo site to showcase the ajax form 👍  https://demo.themeisle.com/pirate-forms

**Comment by rohittm** [comment]
@rodica-andronache @contactashish13 

Check this: [How to enable form submission without reloading the page using AJAX](https://docs.themeisle.com/article/909-how-to-enable-form-submission-without-reloading-the-page-using-ajax) and let me know if there are any edits or corrections that can be done.

**Comment by rodica-andronache** [comment]
@rohittm looking good 👍 Make sure you mention the doc, in the main doc also, I think it would make it easier to be found. And you can also create the page on the demo and save it as draft until the release. Thanks :)

**Comment by rohittm** [comment]
@rodica-andronache here: https://demo.themeisle.com/pirate-forms/ajax-forms/

**Comment by rodica-andronache** [comment]
thank you 👍
