### ISSUE TITLE
change subscription form

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate-forms#306]
@contactashish13 I would need to remove the current subscription form we have in pirate forms ( the one from the sidebar in the general settings ) where users can subscribe to our list.

I have created a subscription form in sendinblue, can you embed this instead of the old one. it will need some style tweaks to match the old design.
 
[form code.txt](https://github.com/Codeinwp/pirate-forms/files/2030278/form.code.txt)
cc @rodica-andronache

**Comment by contactashish13** [comment]
@selul the existing form used to also show that the user was already subscribed. Do you want to remove that functionality?

**Comment by contactashish13** [comment]
@selul have removed that functionality. PR: https://github.com/Codeinwp/pirate-forms/pull/312
