### ISSUE TITLE
Checkbox CSS Issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/pirate-forms#308]
The checkbox created from the option shows up oversized and not inline with the label on some of our themes like Zerif Lite and Parallax One:

![image](https://user-images.githubusercontent.com/10324144/40512632-768d8fe8-5f71-11e8-9b1e-044cffff0351.png)

**Comment by ineagu** [comment]
cc @rodica-andronache , please use some visual tests before releases on multiple themes.
