### ISSUE TITLE
Check/Integrate Pirate Forms with WP 4.9.6

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#310]
https://prnt.sc/jp6adf

@contactashish13 please check the latest options in wp 4.9.6 https://wptavern.com/wordpress-4-9-6-beta-1-adds-tools-for-gdpr-compliance and see how Pirate Forms ( free and pro ) integrates with it. 

If it's not integrated, we need to check on how we can do this. 
Let me know your thoughts on this :)

**Comment by rodica-andronache** [comment]
@contactashish13 is looking good :D Yes, for the pro thing. And yes, we'll update the readme too, thanks for letting me know 👍

**Comment by contactashish13** [comment]
PR for pro: https://github.com/Codeinwp/pirate-forms-pro/pull/76

For exporting, I'm doing nothing extra in pro. Do you want to let the user know that their account has been registered on these integrations?

For erasing, I'm removing the contact from the integrations.

I will need accounts for campaign monitor and aweber as they are paid.

**Comment by contactashish13** [comment]
development still pending, reopening.
