### ISSUE TITLE
Store checkbox state in the database

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#311]
@contactashish13 we need to store in the database the fact that the user has clicked on the checkbox (for GDPR). This way, Pirate Forms users can prove they have consent.

From what I've seen the checkbox state is not saved in the database or in the email content. Am I missing something?

**Comment by contactashish13** [comment]
@rodica-andronache the checkbox in pro is a custom field so it has to be manually added to the email content by using the magic tags. The magic tags list all the custom fields.

I've added support for adding checkbox in lite although even here the magic tags would need to be manually added. PR: https://github.com/Codeinwp/pirate-forms/pull/313

Have added test cases for checking this as well.

**Comment by rodica-andronache** [comment]
@contactashish13 I got two notices one in the dashboard https://prnt.sc/jrnfp3 and one on the form page https://prnt.sc/jrnfvd Could you please test with WP DEBUG enabled? Thank you :D

**Comment by contactashish13** [comment]
@rodica-andronache these have already been fixed in a previous PR. I don't remember which one (there are 4 active PRs) but this should be okay when you merge.

**Comment by rodica-andronache** [comment]
@contactashish13 ok for the warnings, but I don't understand here, how the checkbox is saved in the database. From what I've tested with the lite version, there is nothing about the checkbox either in the Entries or in the database. How is this working?

**Comment by contactashish13** [comment]
@rodica-andronache the checkbox is a field like all other fields. So it will need to be included in the email template, if it has been customized. If it has not been customized, the default email template will contain the checkbox field as well.


![image](https://user-images.githubusercontent.com/12953439/41528763-9c556066-7308-11e8-8058-adc70938330c.png)

**Comment by rodica-andronache** [comment]
ok, thank you :D  I updated the doc here too https://docs.themeisle.com/article/886-gdpr-and-pirate-forms
