### ISSUE TITLE
Does not go full width

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/pirate-forms#35]
We have this message from a client: 

Using Pirate Forms for Parallax One Plus, I noticed the form does not go full width on desktop displays. Mobile devices seem okay. I was able to apply a fix by adding the following with the Simple Custom CSS plugin. Essentially, all I added was, width: 100%;

Code:
.widget-box {
float: none;
display: inline-block;
margin-right: -4px;
vertical-align: top;
text-align: left;
width: 100%;
}

**Comment by rodica-andronache** [comment]
@mileamadalin aici ar trebui un pic mai mult context. Nu prea am de unde sa stiu unde anume a pus pirate forms. Daca mai ai datele, te rog,sa specifici aici daca nu, sa inchizi issue-ul

**Comment by mileamadalin** [comment]
@rodica-andronache era vorba de contact form-ul de pe contact page. Vad ca este destul de veche problema. Poate s-a rezolvat intre timp.
