### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/pirate-forms#38]
Hi guys,

Is there a way to enable PGP encryption for emails sent using the contact form?

If this is not an option, what changes would I need to make in order to replace Pirate Forms with a plugin like SimpleSecure?

Thanks
Zach

@rodica-andronache

**Comment by rodica-andronache** [comment]
@ineagu what do you think about this? I think it's a bit to complex for our plugin, if we want to keep it simple.
Can we close this?

**Comment by ineagu** [comment]
yep, for now
