### ISSUE TITLE
recaptcha on mobile

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#39]
http://themeisle.com/forums/topic/recaptcha-issues-on-mobile-support-of-alternative/

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/zerif-lite/issues/438

**Comment by rodica-andronache** [comment]
Please try and see if you can find a solution to make the current recaptcha work on mobile, like it does when used with Tweentysixteen for example. If not, we can discuss and see if we can find another solution, for mobile, like the user suggested in the first link

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , there is not much I can do here. I think we have two options:
1. Recommend some custom css, something like this:

`@media screen and (max-width: 380px){
	#rc-imageselect, .g-recaptcha {
		transform:scale(0.50);
		-webkit-transform:scale(0.50);
		transform-origin:0 0;
		-webkit-transform-origin:0 0;
	}
}`

2. Add support for [Really Simple CAPTCHA](https://wordpress.org/plugins/really-simple-captcha/) . Maybe recommend this plugin and add an option to choose between google recaptcha (not responsive) and RSC (responsive).

**Comment by mohdshakeel** [comment]
Hi,
Just use this custom css code to resolve pirate forms recaptcha nonclickable the issue.
**.pirate_forms_wrap .form_field_wrap {
   clear: both; !important;
}**
