### ISSUE TITLE
Redesign How to use tab

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#76]
http://prntscr.com/b50q4w

Maybe add a preview of the plugin used with Zerif

And maybe add some text like this: "If you want a more complex contact form plugin please check this link http://www.codeinwp.com/blog/best-contact-form-plugins-wordpress/ "

**Comment by rodica-andronache** [comment]
@abaicus this should also be added:
Maybe add a preview of the plugin used with Zerif

And maybe add some text like this: "If you want a more complex contact form plugin please check this link http://www.codeinwp.com/blog/best-contact-form-plugins-wordpress/ "

**Comment by abaicus** [comment]
Sorry! Forgot about the link. I'll do it right away :D

**Comment by abaicus** [comment]
Solved in 097d50dae959c7b24134fc50591d36d360795514.
