### ISSUE TITLE
Investigate issue with Pirate Forms and cyrillic characters

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pirate-forms#93]
http://themeisle.com/forums/topic/pirate-forms-and-name-in-cyrillic-issue/

**Comment by contactashish13** [comment]
@rodica-andronache I'm not able to access the link. Can you please check?

**Comment by rodica-andronache** [comment]
@contactashish13 i'm not able to access this either, as the forums are closed. I'm gonna close this, sorry :)
